### ISSUE TITLE
Enhance Pyrsia Installer :: Run pyrsia_node as a service at start up

### ISSUE THREAD

**Issue by dasmanas** [pyrsia/pyrsia#1202]
### Suggestion details

Enhance Pyrsia Installer :: Run pyrsia_node as a service at start up

**Comment by dasmanas** [comment]
Facing issues while starting `pyrsia_node` as service.

```
 2022-11-09T11:42:11.818Z DEBUG pyrsia_node > Parse CLI arguments
 2022-11-09T11:42:11.820Z DEBUG pyrsia_node > Create p2p components
 2022-11-09T11:42:11.820Z ERROR pyrsia::util::keypair_util > Error initializing Pyrsia Key Pair directory, error is: Failed to create key pair directory Some("pyrsia")
thread 'main' panicked at 'Error initializing Pyrsia Key Pair directory, error is: Failed to create key pair directory Some("pyrsia")', src/util/keypair_util.rs:58:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2022-11-09T11:42:11.820Z ERROR pyrsia::util::keypair_util > Initialization of Pyrsia Key Pair directory panicked!
```

**Comment by dasmanas** [comment]
> Facing issues while starting `pyrsia_node` as service.
> 
> ```
> 2022-11-09T11:42:11.818Z DEBUG pyrsia_node > Parse CLI arguments
> 2022-11-09T11:42:11.820Z DEBUG pyrsia_node > Create p2p components
> 2022-11-09T11:42:11.820Z ERROR pyrsia::util::keypair_util > Error initializing Pyrsia Key Pair directory, error is: Failed to create key pair directory Some("pyrsia")
> thread 'main' panicked at 'Error initializing Pyrsia Key Pair directory, error is: Failed to create key pair directory Some("pyrsia")', src/util/keypair_util.rs:58:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 2022-11-09T11:42:11.820Z ERROR pyrsia::util::keypair_util > Initialization of Pyrsia Key Pair directory panicked!
> ```

Issue has been resolved as soon as the service has given `root_dir` & `working_dir` through brew service. Pyrsia Node writes few files and directories. Therefore service working directory has to have the permission for the current user.
