### ISSUE TITLE
Unit Test: docker::v2::storage::blobs::tests::test_get_space_available failed

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#643]
Details:
```
running 1 test
[2022-05-02T21:31:07Z INFO  pyrsia::artifacts_repository::artifact_manager] Creating directory /private/var/folders/cr/h8bkj2yx251f97xgspz80cq40000gp/T/privaterPM8iS/PyrsiaTest/SHA256
[2022-05-02T21:31:07Z INFO  pyrsia::artifacts_repository::artifact_manager] Creating directory /private/var/folders/cr/h8bkj2yx251f97xgspz80cq40000gp/T/privaterPM8iS/PyrsiaTest/SHA512
[2022-05-02T21:31:07Z INFO  pyrsia::artifacts_repository::artifact_manager] Creating an ArtifactManager with a repository in /private/var/folders/cr/h8bkj2yx251f97xgspz80cq40000gp/T/privaterPM8iS/PyrsiaTest
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueIncorrect(NotNumber('p'))', src/node_manager/handlers.rs:142:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
   4: pyrsia::node_manager::handlers::get_space_available
             at /Users/xuefeihan/project/rust/fishseabowl/pyrsia/src/node_manager/handlers.rs:141:37
   5: pyrsia::docker::v2::storage::blobs::tests::test_get_space_available::child::{{closure}}
             at /Users/xuefeihan/project/rust/fishseabowl/pyrsia/src/docker/v2/storage/blobs.rs:125:13
   6: pyrsia::docker::v2::storage::blobs::tests::test_get_space_available::child
             at /Users/xuefeihan/project/rust/fishseabowl/pyrsia/src/docker/v2/storage/blobs.rs:118:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
   8: rusty_fork::fork::fork::{{closure}}
             at /Users/xuefeihan/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-fork-0.3.0/src/fork.rs:107:23
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:280:13
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  11: std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  12: ___rust_try
  13: std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  14: std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  15: rusty_fork::fork::fork_impl
             at /Users/xuefeihan/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-fork-0.3.0/src/fork.rs:117:15
  16: rusty_fork::fork::fork
             at /Users/xuefeihan/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-fork-0.3.0/src/fork.rs:103:5
  17: pyrsia::docker::v2::storage::blobs::tests::test_get_space_available
             at /Users/xuefeihan/project/rust/fishseabowl/pyrsia/src/docker/v2/storage/blobs.rs:118:5
  18: pyrsia::docker::v2::storage::blobs::tests::test_get_space_available::{{closure}}
             at /Users/xuefeihan/project/rust/fishseabowl/pyrsia/src/docker/v2/storage/blobs.rs:118:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test docker::v2::storage::blobs::tests::test_get_space_available ... FAILED

failures:

failures:
    docker::v2::storage::blobs::tests::test_get_space_available

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 50 filtered out; finished in 0.10s
```

**Comment by fishseabowl** [comment]
Unit Test: node_manager::handlers::tests::test_disk_usage also fails. I guess there is the same root cause:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueIncorrect(NotNumber('p'))', src/node_manager/handlers.rs:155:10
```

**Comment by betarelease** [comment]
This hasn't failed in a long time. Can we close this @fishseabowl ?
